version: '3'

services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - '.env'
#    ports:
#      - '8000:8000'
#    depends_on:
#      - postgres
#      - redis
#      - rabbitmq

#  scheduler

#  decider

  redis:
    image: 'redis:3.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  rabbitmq:
    image: 'rabbitmq:3.7.3-management'
    ports:
      - '8080:15672'
      - '5672:5672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq/flow'

  postgres:
    image: 'postgres:9.5-alpine'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/flow'

volumes:
  postgres:
  redis:
  rabbitmq_data:
