# Generated by Django 2.0.5 on 2018-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleversion',
            name='status',
            field=models.CharField(choices=[('preview', 'preview'), ('published', 'Published'), ('ready', 'ready')], default='preview', max_length=50),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
