# Generated by Django 2.0.5 on 2018-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180515_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
    ]
