#%RAML 1.0
title: eLife's Libero walking skeleton

baseUri: http://localhost:8085

resourceTypes:
    articles: !include articles.raml

types:
    ArticleVersionFront:
        type: !include http://api-dummy-nginx:80/schemas/elife/article/front.rng # don't work as contains localhost references
        example: !include http://api-dummy-nginx:80/articles/00666/latest/front
    ArticleVersionBody:
        type: !include http://api-dummy-nginx:80/schemas/elife/article/body.rng # don't work as contains localhost references
        example: !include http://api-dummy-nginx:80/articles/00666/latest/body

/articles:
    type: articles
