services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Libero\Journal\:
        resource: '../src/*'
        exclude: '../src/{namespaces.php,Kernel.php}'

    Libero\Journal\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
