openapi: 3.0.1

info:
    title: Libero walking skeleton articles
    license:
        name: MIT

servers:
    - url: http://localhost:8081/articles

paths:

    /:
        get:
            summary: List all articles
            responses:
                '200':
                    description: List of articles
                    content:
                        application/xml:
                default:
                    $ref: errors.yaml#components/responses/error

    /{id}:
        delete:
            summary: Delete an article
            parameters:
                - name: id
                  in: path
                  description: Article ID
                  required: true
                  schema:
                      type: string
                      pattern: ^[A-Za-z0-9\-._]+$
            responses:
                '202':
                    description: Deletion request accepted
                default:
                    $ref: errors.yaml#components/responses/error
        post:
            summary: Create an article version
            parameters:
                - name: id
                  in: path
                  description: Article ID
                  required: true
                  schema:
                      type: string
                      pattern: ^[A-Za-z0-9\-._]+$
            requestBody:
                content:
                    application/xml:
            responses:
                '202':
                    description: Creation request accepted
                default:
                    $ref: errors.yaml#components/responses/error

    /{id}/{version}:
        delete:
            summary: Delete an article version
            parameters:
                - name: id
                  in: path
                  description: Article ID
                  required: true
                  schema:
                      type: string
                      pattern: ^[A-Za-z0-9\-._]+$
            responses:
                '202':
                    description: Deletion request accepted
                default:
                    $ref: errors.yaml#components/responses/error
        put:
            summary: Replace an article version
            parameters:
                - name: id
                  in: path
                  description: Article ID
                  required: true
                  schema:
                      type: string
                      pattern: ^[A-Za-z0-9\-._]+$
                - name: version
                  in: path
                  description: Article version
                  required: true
                  schema:
                      type: integer
                      minimum: 1
            requestBody:
                content:
                    application/xml:
            responses:
                '202':
                    description: Replace request accepted
                default:
                    $ref: errors.yaml#components/responses/error

    /{id}/{version}/{part}:
        get:
            summary: Get an article version part
            parameters:
                - name: id
                  in: path
                  description: Article ID
                  required: true
                  schema:
                      type: string
                      pattern: ^[A-Za-z0-9\-._]+$
                - name: version
                  in: path
                  description: Article version
                  required: true
                  schema:
                      oneOf:
                          - type: integer
                            minimum: 1
                          - type: string
                            enum: [latest]
                - name: part
                  in: path
                  description: Article part
                  required: true
                  schema:
                      type: string
                      pattern: ^[A-Za-z0-9\-._]+$

            responses:
                '200':
                    description: Article version
                    content:
                        application/xml:
                default:
                    $ref: errors.yaml#components/responses/error
