# Generated by Django 2.0.5 on 2018-05-17 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9\\-._]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preview', 'preview'), ('published', 'published'), ('ready', 'ready')], default='preview', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('model', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('article_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='articles.ArticleVersion')),
            ],
        ),
    ]
