# Generated by Django 2.0.5 on 2018-05-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180514_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='text',
            new_name='content',
        ),
    ]
