# Generated by Django 2.0.5 on 2018-05-16 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_content_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9\\-._]+$')]),
        ),
    ]
