version: '3'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - 'postgres:/var/lib/postgresql/data'

    rabbitmq: # ONLY USED AS A DUMMY EVENT BUS!
        image: 'rabbitmq:3.7.3-management'
        ports:
            - '8090:15672'
            - '5672:5672'
        volumes:
            - 'rabbitmq:/var/lib/rabbitmq'

    webserver:
        build:
          context: .
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - './dags:/usr/local/airflow/dags'
            - './plugins:/usr/local/airflow/plugins'
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
          context: .
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
          context: .
        depends_on:
            - webserver
        volumes:
            - './dags:/usr/local/airflow/dags'
            - './plugins:/usr/local/airflow/plugins'
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler

    worker:
        build:
          context: .
        depends_on:
            - scheduler
        volumes:
            - './dags:/usr/local/airflow/dags'
            - './plugins:/usr/local/airflow/plugins'
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker
volumes:
  postgres:
  rabbitmq:
